<a href="https://colab.research.google.com/github/minjoo1412/2020_AI/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_2%EC%B0%A8_%EC%8B%A4%EC%8A%B5%EC%BD%94%EB%93%9C_%EC%B6%9C%EC%A0%9C%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Data loading

from sklearn.datasets import load_wine

dataset = load_wine()
data = dataset.data
labels = dataset.target

print(data)
print(labels)
print(data.shape)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
(178, 13)


In [16]:
# Split data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.3) 
print(len(x_train), len(x_test), type(x_train))

print(x_test)
print(y_test)

124 54 <class 'numpy.ndarray'>
[[1.164000e+01 2.060000e+00 2.460000e+00 2.160000e+01 8.400000e+01
  1.950000e+00 1.690000e+00 4.800000e-01 1.350000e+00 2.800000e+00
  1.000000e+00 2.750000e+00 6.800000e+02]
 [1.308000e+01 3.900000e+00 2.360000e+00 2.150000e+01 1.130000e+02
  1.410000e+00 1.390000e+00 3.400000e-01 1.140000e+00 9.400000e+00
  5.700000e-01 1.330000e+00 5.500000e+02]
 [1.286000e+01 1.350000e+00 2.320000e+00 1.800000e+01 1.220000e+02
  1.510000e+00 1.250000e+00 2.100000e-01 9.400000e-01 4.100000e+00
  7.600000e-01 1.290000e+00 6.300000e+02]
 [1.388000e+01 1.890000e+00 2.590000e+00 1.500000e+01 1.010000e+02
  3.250000e+00 3.560000e+00 1.700000e-01 1.700000e+00 5.430000e+00
  8.800000e-01 3.560000e+00 1.095000e+03]
 [1.233000e+01 1.100000e+00 2.280000e+00 1.600000e+01 1.010000e+02
  2.050000e+00 1.090000e+00 6.300000e-01 4.100000e-01 3.270000e+00
  1.250000e+00 1.670000e+00 6.800000e+02]
 [1.242000e+01 1.610000e+00 2.190000e+00 2.250000e+01 1.080000e+02
  2.000000e+00 2.09000

In [17]:
# Convert to tensor

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset


x_train = torch.from_numpy(x_train).float()
y_train = torch.from_numpy(y_train).long()

x_test = torch.from_numpy(x_test).float()
y_test = torch.from_numpy(y_test).long()
print(type(x_train))

<class 'torch.Tensor'>


In [18]:
# Generating dataset

train_set = TensorDataset(x_train, y_train)
test_set = TensorDataset(x_test, y_test)



"""
문제 1 : train_loader 생성 ( 5점 )

조건 1 : train_set 변수 활용
조건 2 : 배치 크기는 16
조건 3 : shuffle 사용
"""
train_loader = DataLoader(dataset=test_set, batch_size=16, shuffle=True, num_workers=2)


In [24]:
# Construct model

class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(3, 6, 5)
    self.pool = nn.MaxPool2d(2, 2)
    self.conv2 = nn.Conv2d(6, 16, 5)
    self.fc1 = nn.Linear(16 * 5 * 5, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
    



  def forward(self,x):
    
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16 * 5 * 5)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    
    return x

model = Model()
print(model)


Model(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [12]:
# Configure optimizer
import torch.optim as optim

"""
문제 4 : Optimizer 생성 (5점)

조건 1 : SGD 생성
조건 2 : 학습률 0.001
조건 3 : Momentum 0.9
"""
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)### 코드 작성 위치


"""
문제 5 : 손실 함수 생성 (5점 )

조건 1 : Cross Entropy Loss 생성
"""
criterion = nn.CrossEntropyLoss()### 코드 작성 위치

NameError: ignored

In [ ]:
# Training

epochs = 200
losses = list()
accuracies = list()

for epoch in range(epochs):
  epoch_loss = 0  
  epoch_accuracy = 0


  for x, y in train_loader:

  """
  문제 6 : Training code 작성 ( 6점 )

  조건 1 : 튜토리얼에서 학습했던 내용과 같이 학습 코드 작성

  """
    ### 코드 작성 위치


    _, predicted = torch.max(output, dim=1)
    accuracy = (predicted == y).sum().item()
    epoch_loss += loss.item()
    epoch_accuracy += accuracy
  

  epoch_loss /= len(train_loader)
  epoch_accuracy /= len(x_train)
  print("epoch :{}, \tloss :{}, \taccuracy :{}".format(str(epoch+1).zfill(3),round(epoch_loss,4), round(epoch_accuracy,4)))
  
  losses.append(epoch_loss)
  accuracies.append(epoch_accuracy)

  

In [ ]:
# Plot result

import matplotlib.pyplot as plt

plt.figure(figsize=(20,5))
plt.subplots_adjust(wspace=0.2)

plt.subplot(1,2,1)
plt.title("$loss$",fontsize = 18)
plt.plot(losses)
plt.grid()
plt.xlabel("$epochs$", fontsize = 16)
plt.xticks(fontsize = 14)
plt.yticks(fontsize = 14)


plt.subplot(1,2,2)
plt.title("$accuracy$", fontsize = 18)
plt.plot(accuracies)
plt.grid()
plt.xlabel("$epochs$", fontsize = 16)
plt.xticks(fontsize = 14)
plt.yticks(fontsize = 14)

plt.show()

In [ ]:
# Test

output = model(x_test)
_, predicted = torch.max(output, dim=1)
accuracy = round((predicted == y_test).sum().item() / len(y_test),4)


print("test_set accuracy :", round(accuracy,4))